### ISSUE TITLE
Validating schema's from referenced parameters fails.

### ISSUE THREAD

**Issue by atehvg** [nijens/openapi-bundle#100]
Parameters defined in the OpenApi documentation can be defined with referenced components. The components define schemas where patterns can be defined to validate valid input. The following configuration is used to activate the parameter validation.

``` yaml
nijens_openapi:
    exception_handling:
        enabled: true

    validation:
        parameter_validation: true

    routing:
        operation_id_as_route_name: true
```
Example of defining the parameter in the OpenApi file with a reference and a schema and failing validation:
``` yaml
      ...
      parameters:
        - $ref: '#/components/parameters/FilterByNumber'
      ...
```
``` yaml
components:
  parameters:
    FilterByNumber:
      name: filterByNumber
      in: query
      required: true
      description: Filter the list by number.
      schema:
        type: string
        pattern: '^[A-Z]{2}[0-9]{4,}$'
    ...
```

Currently, the schema validation does not work and results in an exception with the following stack trace:

```
ErrorException:
Warning: Undefined property: stdClass::$schema

  at vendor/nijens/openapi-bundle/src/Validation/RequestValidator/RequestParameterValidator.php:97
  at Nijens\OpenapiBundle\Validation\RequestValidator\RequestParameterValidator->validateQueryParameter(object(Request), 'filterByNumber', object(stdClass))
     (vendor/nijens/openapi-bundle/src/Validation/RequestValidator/RequestParameterValidator.php:54)
  at Nijens\OpenapiBundle\Validation\RequestValidator\RequestParameterValidator->validate(object(Request))
     (vendor/nijens/openapi-bundle/src/Validation/RequestValidator/CompositeRequestValidator.php:43)
  at Nijens\OpenapiBundle\Validation\RequestValidator\CompositeRequestValidator->validate(object(Request))
     (vendor/nijens/openapi-bundle/src/Validation/EventSubscriber/RequestValidationSubscriber.php:57)
  at Nijens\OpenapiBundle\Validation\EventSubscriber\RequestValidationSubscriber->validateRequest(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:115)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:206)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(RequestEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:122)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (vendor/symfony/http-kernel/HttpKernel.php:159)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:182)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/var/www/vendor/autoload_runtime.php')
     (public/index.php:5)
```

Example of defining the parameter in the OpenApi file with a reference and a schema when validation succeeds:
``` yaml
      ...
      parameters:
        - name: filterByNumber
          in: query
          required: true
          description: Filter the orders by order number.
          schema:
            type: string
            pattern: '^[A-Z]{2}[0-9]{4,}$'
      ...
```
``` json
{
    "type": "about:blank",
    "title": "The request contains errors.",
    "status": 400,
    "detail": "Validation of query parameters failed.",
    "violations": [
        {
            "constraint": "pattern",
            "message": "Does not match the regex pattern ^[A-Z]{2}[0-9]{4,}$",
            "property": "filterByNumber"
        }
    ]
}
```
